site_name: "MBARI's Video Annotation and Reference System"
theme:
    name: material
    logo: https://docs.mbari.org/imgs/mbari-logo.png
extra_css:
    - https://docs.mbari.org/css/mbari.css

plugins:
  - search
  - mermaid2

markdown_extensions:
  - footnotes
  - toc:
      permalink: True