site_name: "MBARI's Video Annotation and Reference System (VARS)"
theme:
    name: material
    logo: https://docs.mbari.org/imgs/mbari-logo.png
extra_css:
    - https://docs.mbari.org/css/mbari.css
    - assets/css/extras.css

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Services: services.md
  - Applications: applications.md

markdown_extensions:
  - footnotes
  - toc:
      permalink: True