[project]
site_name = "MBARI's Video Annotation and Reference System (VARS)"
site_description = "MBARI's Video Annotation and Reference System (VARS)"
site_author = "Brian Schlining"
repo_name = "mbari-org/vars"
repo_url = "https://github.com/mbari-org/vars"


[project.theme]
name = "material"
logo = "assets/images/mbari-logo.png"
# favicon = "assets/images/favicon.ico"
features = [
    "navigation.instant",
    "navigation.indexes",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "content.code.copy",
    "search.highlight",
]
icon.repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preferences"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]

[project.nav]
"Home" = "index.md"
"Getting Started" = "getting-started.md"
"Architecture" = "architecture.md"
"Services" = "services.md"
"Applications" = "applications.md"